export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";


export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
